### ISSUE TITLE
Cross-origin requests

### ISSUE THREAD

**Issue by assaron** [joshua-gould/morpheus.js#1]
Hi Josh,

There are a few minor bugs when I'm running morpheus version locally in Chromium. You does not specify protocol in the external datasets like CCLE and my browser tries to open them via file:// protocol and fails. See the scrennshot
![2016-06-08-130252_956x1059_scrot](https://cloud.githubusercontent.com/assets/1040217/15890784/ee51ec12-2d79-11e6-8c99-79716527cde9.png)

---

Alexey

**Comment by joshua-gould** [comment]
You need to run a server locally using "node server". You can then access
morpheus at localhost:3000.

**Comment by assaron** [comment]
Oh, I see. Don't you want to make it possible to run it serverless? As I understand, only static content is served now, so it should not be a problem,

**Comment by joshua-gould** [comment]
I think you're right. If we change all the URLs to https:// it should work with and without a server.

**Comment by joshua-gould** [comment]
All set now.

**Comment by assaron** [comment]
Thanks!
