### ISSUE TITLE
Cannot adjust tree cut for hierarchical clustering

### ISSUE THREAD

**Issue by kieran-mace** [joshua-gould/morpheus.js#18]
The dotted line used to cut the row dendrogram tree literally touch the side of the browser, it is therefore impossible to use the mouse to click and drag it

<img width="808" alt="screen shot 2018-03-22 at 11 02 39 am" src="https://user-images.githubusercontent.com/18296227/37789223-93a67ec4-2dc0-11e8-8d29-cc42c5bde7a2.png">

**Comment by aakashsur** [comment]
I've experience the same issue, I managed to manipulate the div in browser to add a margin which lets you access the dendrogram cutoff. Should be a simple fix though. 

![image](https://user-images.githubusercontent.com/7614271/39068716-1760cba6-4492-11e8-8c60-efa20e11083f.png)

**Comment by joshua-gould** [comment]
Added margin
