### ISSUE TITLE
Morpheus giving blank page

### ISSUE THREAD

**Issue by mckrti** [joshua-gould/morpheus.js#20]
Hi, I am trying to load a url based JSON.  The JSON is generated on the fly upon hitting that url.  However, Morpheus is not loading the JSON, and just giving a blank page.  It looks like it is the same source as a page that works, but no error, nothing pops up.

    <!DOCTYPE html>
    <meta charset="utf-8">

    <link rel="stylesheet" href="morpheus.js-master/css/morpheus-latest.min.css">
    <script type="text/javascript" src="morpheus.js-master/js/morpheus-external-latest.min.js"></script>
    <script src="morpheus.js-master/js/morpheus-latest.min.js"></script>

    <body>
    <noscript>
        <p>Please enable JavaScript</p>
    </noscript>
    <div id="vis"></div>
    
    <script type="text/javascript">
        morpheus.Util.loadTrackingCode();
        window.onerror = function () {
            morpheus.FormBuilder.showInModal({
                title: 'Error',
                html: 'Oops, something went wrong. Please try again.'
            });
        };

        var searchString = window.location.search;
        if (searchString.length === 0) {
            searchString = window.location.hash;
        }
        var landingPage = new morpheus.LandingPage();
        landingPage.$el.prependTo($(document.body));
        if (searchString.length === 0) {
            landingPage.show();
        } else {
            searchString = searchString.substring(1);
            var keyValuePairs = searchString.split('&');
            var params = {};
            for (var i = 0; i < keyValuePairs.length; i++) {
                var pair = keyValuePairs[i].split('=');
                params[pair[0]] = decodeURIComponent(pair[1]);
            }
            if (params.json) {
                var options = JSON.parse(decodeURIComponent(params.json));
                landingPage.open(options);
            } else if (params.url) { // url to config
                var $loading = morpheus.Util.createLoadingEl();
                $loading.appendTo($('#vis'));
                morpheus.Util.getText(params.url).done(function (options) {
                    if (typeof (options) === 'string') {
                        options = JSON.parse(options);
                    }
                    landingPage.open(options);
                }).fail(function (err) {
                    console.log('Unable to get config file');
                    landingPage.show();
                }).always(function () {
                    $loading.remove();
                });

            } else {
                landingPage.show();
            }
        }
    </script>
    
    <script>
        if ((window.location.protocol === 'https:' || window.location.protocol === 'http:') &&
            'serviceWorker' in navigator) {
            navigator.serviceWorker
                .register('sw.js');
        }

    </script>
    </body>

**Comment by joshua-gould** [comment]
Can you send me an example JSON object that fails and the full URL you're using to load Morpheus? Thanks.

**Comment by mckrti** [comment]
Is there a way I could directly email you?  This is being developed on a development instance.

**Comment by joshua-gould** [comment]
Please send an email to morpheus at broadinstitute.org
