### ISSUE TITLE
Possible bug with URL loading

### ISSUE THREAD

**Issue by evilfer** [joshua-gould/morpheus.js#21]
Hi,

It looks like there is a possible bug here:

https://github.com/cmap/morpheus.js/blob/master/index.html#L67

I believe that in line 67 (https://github.com/cmap/morpheus.js/blob/master/index.html#L67) the code should use function `then`, not `done`. So the code should be:

```
morpheus.Util.getText(params.url).then(function (text) {
```

What do you think?

EDIT:

Similarly:

Line 70 should use `catch`, instead of `fail`
Line 73 should use `finally`, instead of `always`

**Comment by joshua-gould** [comment]
Thanks, this is fixed now.
