### ISSUE TITLE
Fit to window onload configuration

### ISSUE THREAD

**Issue by mxposed** [joshua-gould/morpheus.js#22]
Hi

Thank you for this great tool. I wonder if it is possible to configure morpheus to display Fit To Window view onload?
I tried using `tools: [{"name": "Fit To Window"}]`, but the code assumed the action would have a gui and raises an error.

```
morpheus-latest.min.js:1 Uncaught (in promise) TypeError: action.gui is not a function
    at morpheus-latest.min.js:1
    at Function.m.each.m.forEach (morpheus-external-latest.min.js:20)
    at morpheus.HeatMap._init (morpheus-latest.min.js:1)
    at morpheus-latest.min.js:1
```

**Comment by joshua-gould** [comment]
Thanks for reporting the issue. It's fixed now.
