### ISSUE TITLE
Cannot filter on multiple categories

### ISSUE THREAD

**Issue by ecerami** [joshua-gould/morpheus.js#23]
I cannot seem to filter columns on multiple categories.

Here is an example from a public data set.

Steps to recreate:

1.  I loaded up the AML Mutation Data Set.
2. Clicked Tools --> Filter
3. Clicked Columns
4. Clicked "Pass all filters"
5. Clicked Add
6. Selected Gender --> Female

At this point, the matrix filters nicely.

7. Clicked Add
8. Selected Ethnicity --> Not Hispanic or Latino

At this point, the matrix is filtered by ethnicity, but my original gender filter no longer works.  If I click male/female, still nothing happens.  Clicking pass all filters also seems to have no effect.

**Comment by joshua-gould** [comment]
What URL are you accessing Morpheus at? Thanks.

**Comment by ecerami** [comment]
I am using https://software.broadinstitute.org/morpheus/

**Comment by joshua-gould** [comment]
Thanks for reporting. Fixed now.

**Comment by ecerami** [comment]
thank you!
