### ISSUE TITLE
About missing value in tSNE analysis

### ISSUE THREAD

**Issue by wososa** [joshua-gould/morpheus.js#27]
Dear authors,

Could you please kindly explain how you handles the missing values for tSNE analysis?

Thanks,
Woody

**Comment by joshua-gould** [comment]
Missing values are skipped when computing distances.

**Comment by wososa** [comment]
Hi @joshua-gould ,

thanks for quick reply. If a row has a 1-2 NA values, would the whole row be dropped before running tSNE? 

Best,
Woody

**Comment by joshua-gould** [comment]
Only elements that are missing in either of the 2 rows that are used to
compute pairwise distances are dropped.

**Comment by wososa** [comment]
Hi @joshua-gould ,

would that make the number of rows for each column inconsistent? PCA requires the same number of rows for each column, did tSNE not have this constraint?

thanks,
Woody

**Comment by joshua-gould** [comment]
tSNE requires a distance matrix as input. When computing the distance between a pair of samples, Morpheus ignores feature coordinates with a missing value in either sample.

**Comment by wososa** [comment]
Hi @joshua-gould ,

Wonderful~ I understand now.

Thanks,
Woody
