### ISSUE TITLE
Annotation feature for cells

### ISSUE THREAD

**Issue by mxposed** [joshua-gould/morpheus.js#33]
Hello, thank you for the amazing tool.
I was wondering if there is or was a feature to annotate cells in the heatmap with text, analogous to seaborn (second example here https://seaborn.pydata.org/generated/seaborn.heatmap.html)

If not, where would one start to implement this?

**Comment by joshua-gould** [comment]
Like this? If so, please select View>Options>Display and select "Show Values"

<img width="460" alt="image" src="https://github.com/cmap/morpheus.js/assets/5237151/941dfe8f-5116-4a7e-8c6d-34fbfd0ccf2b">

**Comment by mxposed** [comment]
Yes, like this, thank you! My specific usecase is to plot –log10(pvalue) heatmap and highlight significant cells. Dimensions are ~200 columns by ~50 rows.

Is it possible to pass a separate table of stars or empty strings for display?
Is it possible to enable these annotation in config in javascript?

**Comment by joshua-gould** [comment]
Please see https://software.broadinstitute.org/morpheus/configuration.html for configuration info. You need to pass 2 series-the first contains your p-values and the 2nd a matrix of 1s and 0s where 1 indicates significant. Then, you can render a circle in using View>Options>Conditional Rendering. 

Example: 
<img width="357" alt="image" src="https://github.com/cmap/morpheus.js/assets/5237151/8a11f5b5-f806-4c9d-b772-089604ca9acd">

**Comment by mxposed** [comment]
Thank you very much!
