### ISSUE TITLE
Right-click dialog for column metadata gets clipped

### ISSUE THREAD

**Issue by assaron** [joshua-gould/morpheus.js#4]
Sometimes right-click dialog for column metadata is displayed incorrectly (see the screenshot). It happens after I do hierarchical clustering.

![2016-11-27-180925_1366x739_scrot](https://cloud.githubusercontent.com/assets/1040217/20649289/11febbc4-b4cd-11e6-87d7-cfe6b491e8fa.png)

**Comment by joshua-gould** [comment]
Fixed positioning
